#
# This example configuration file illustrates every single thing that can be configured.
#
settings:
  # Polling interval in milliseconds
  pollingInterval: 5000
  # HTTP port to serve the web interface on
  httpPort: 8080

circuits:
  # A "virtual" type circuit with type = "main". The circuit type defaults to "circuit".
  - name: Main total
    type: main
    sensor:
      # Virtual sensors combine the power readings from child sensors
      type: virtual
      virtual:
        children:
          - Main L1
          - Main L2
          - Main L3
  # An "unmetered" type circuit
  - name: Main total unmetered
    type: main
    sensor:
      # Unmetered sensors derive their readings by subtracting child sensor values from the parent sensor.
      type: unmetered
      unmetered:
        parent: Main total
        children:
          - Vägg vardagsrum
          - Vägg kök
          - Vägg arbetsrum
      filters:
        clamp: positive # Don't allow negative values
  # A IotaWatt main circuit, phase A/L1
  - name: Main L1
    type: main
    phase: L1
    parent: Main total
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Main_L1
  # A IotaWatt main circuit, phase B/L2
  - name: Main L2
    type: main
    phase: L2
    parent: Main total
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Main_L2
  # A IotaWatt main circuit, phase C/L3
  - name: Main L3
    type: main
    phase: L3
    parent: Main total
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Main_L3
  # A IotaWatt circuit. "parent" indicates that this circuit's readings are part of the parent's readings too.
  - name: Vägg vardagsrum
    parent: Main L3
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Vagg_Vardagsrum
  # Another IotaWatt circuit.
  - name: Vägg kök
    parent: Main L3
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Vagg_Kok
      filters:
        highPass: 2 # Ignore loads less than 2 watts (show as 0)
    group: Matlagning
  # Yet another IotaWatt circuit. This one has a different "parent" than the others.
  - name: Vägg arbetsrum
    parent: Main L1
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Vagg_Sovrum1
  # A Shelly circuit. "meter" 0 means use the first energy meter. Some devices have two channels, this is used to
  # differentiate between those.
  - name: Rack
    parent: Main L1
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.61
        meter: 0
  # Two Shelly circuits that are backed by the same Shelly 2.5 relay, using different values for "meter".
  - name: Belysning köksbänkar
    parent: Main L3
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.44
        meter: 0
    group: Belysning
  - name: Belysning köksfönster
    parent: Main L3
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.44
        meter: 1
    group: Belysning
  # A Shelly "Gen2" "PM" circuit. "type" is by default "gen1". "gen2-pm" devices include e.g. Shelly Plus 1PM
  - name: Kylskåp + frys källare
    parent: Main L2
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.66
        type: gen2-pm
        meter: 0
  # A main circuit using a Shelly Pro 3EM. Here the "type" is set to "gen2-em". "meter" should normally be set to 0,
  # in theory there can be multiple different meters in the same product.
  - name: Main L1
    type: main
    phase: L1
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.67
        type: gen2-em
        meter: 0
        phase: a
  # A circuit with a Modbus sensor
  - name: Inverter/chargers
    type: circuit
    sensor:
      type: modbus
      modbus:
        address: 10.112.4.250
        port: 502
        unit: 100
        register: h@866/int16 # same as just 866
      filters:
        clamp: positive

#
# Characteristics. Characteristics mean voltage and frequency, and potentially other non-power related readings.
#
characteristics:
  # Characteristics from each phase in a three-phase system using both a IotaWatt sensor and a Shelly Pro 3 EM.
  - name: Main L1
    phase: L1
    sensor:
      type: iotawatt
      iotawatt:
        address: 10.112.4.4
        name: Input_0
  - name: Main L2
    phase: L2
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.67
        type: gen2-em
        meter: 0
        phase: b
  - name: Main L3
    phase: L3
    sensor:
      type: shelly
      shelly:
        address: 10.112.4.67
        type: gen2-em
        meter: 0
        phase: c

#
# Publishers. Publishers send the gathered data to other systems. If you don't want to publish the data anywhere,
# use an empty list:
#
# publishers:
#
publishers:
  # InfluxDB publisher. Only InfluxDB v2 is supported.
  - type: influxdb
    settings:
      url: http://10.110.1.6:8086/
      organizationId: organisation id
      bucket: eachwatt
      apiToken: token
  # Console publisher. Simply logs readings to stdout. Useful for debugging and to verify the application is running.
  - type: console
  # MQTT publisher
  - type: mqtt
    settings:
      brokerUrl: mqtt://10.110.1.3:1883
      # Optional Home Assistant auto-discovery support
      homeAssistant:
        autoDiscovery: true
        deviceIdentifier: eachwatt
