name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Check formatting
        run: npm run prettier-check
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Run eslint
        run: npm run lint
  jest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Run tests
        run: npm run test
  webif-prettier:
    name: Check web interface formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webif
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Check formatting
        run: npm run prettier-check
  webif-eslint:
    name: Lint web interface
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webif
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Run eslint
        run: npm run lint
  webif-svelte-check:
    name: svelte-check web interface
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webif
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-workspace
      - name: Run svelte-check
        run: npm run check
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the image
        run: docker build -t jalle19/eachwatt:latest .
