name: Publish Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the image
        run: docker build -t ghcr.io/jalle19/eachwatt:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish the image
        run: docker push ghcr.io/jalle19/eachwatt:latest
