name: Publish Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the image
        run: docker build -t ghcr.io/jalle19/eachwatt:latest .
      - name: Publish the image
        run: docker push ghcr.io/jalle19/eachwatt:latest
